[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/патчада.html"
  status = 200

[[redirects]]
  from = "/api/market"
  to = "/.netlify/functions/market"
  status = 200
